### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by YOSSHIXD** [Yululinqq/Vrpos#1]
issueissueissueissueissueissueissueissueissueissueissueissueissueissueissueissueissueissueissueissueissueissueissueissueissueissue

**Comment by Yululinqq** [comment]
2021年の健康洗浄方法。まず、コンピューターにpsyjまたはEclipseをインストールします。の隣に
https://github.com/SatelliteClient/Satelliteにアクセスし、コード->郵便番号をダウンロードします。これはZip形式でダウンロードできます。次に、Intellijを開き、最初に印刷したzipファイルからUnZipを実行します。ブラウザを右クリックして、UnZipを実行します。それまでの間、お気に入りのディレクトリを取得して、準備をしてください。次に、Intellijに戻り、.GRADLEを開きます。次に、GRADLE同期が完了するのを待ち、構成でDecompワークスペースを実行して、再び完了するのを待ちます。次に、gradlew genIntellijRunsを実行し、完了したら、コードを編集して実行し、クライアントを実行します。これでクリーニングスライドは完成です。

**Comment by Yululinqq** [comment]
おいCLose
